# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dbcb622011bf01d3f4a5232e6bd62115f489bc3b50b6d9cd4640b61847ec96eff708c1e3ae8d1bc694f99ca0b6032f4cc4c7fcf249de9e6f43413fee457701f

test:
  secret_key_base: d68dd61bfff3857451634bdc8c81f478d4e1c783206818ff700c5790970afdd04a7e7af7129d6140caabf0f2a09575276cbaa8d4c0cde36e96a23b66ac2b8601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
